// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfjZUQktonvXXk0eAm1QxouNliIrXmNMQ',
    appId: '1:567222871872:web:57419b8d7d8ccb456c3ca5',
    messagingSenderId: '567222871872',
    projectId: 'binbot-model',
    authDomain: 'binbot-model.firebaseapp.com',
    storageBucket: 'binbot-model.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAodAYSoNAoxw8hOGtWVj3ttZ3sGSAIbTw',
    appId: '1:567222871872:android:a8706863ea5b745b6c3ca5',
    messagingSenderId: '567222871872',
    projectId: 'binbot-model',
    storageBucket: 'binbot-model.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2uEqikifU9CjA6_1xyHaNO_HAv6n1g8',
    appId: '1:567222871872:ios:0d7a76ba09b6f7fc6c3ca5',
    messagingSenderId: '567222871872',
    projectId: 'binbot-model',
    storageBucket: 'binbot-model.appspot.com',
    iosBundleId: 'com.example.binbotApp',
  );
}
